{% set name = "csm" %}
{% set version = "3.0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sminster/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dcb2f1bbdfd3b506a9646a5bfcc00026ed161cd1bbb61452498d2537f3b8706e
  patches:
    - patches/add_cmake.patch   # Adds the CMake build system

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake
    - ninja

test:
  commands:
    - test -e $PREFIX/lib/libcsmapi.so  # [linux]
    - test -e $PREFIX/lib/libcsmapi.dylib  # [osx]
    - test -e $PREFIX/include/csm/Isd.h  # [not win]
    - test -e $PREFIX/include/csm/csm.h  # [not win]
    - if not exist %LIBRARY_BIN%\csmapi.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\csmapi.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\csm\Ellipsoid.h exit 1  # [win]

about:
  home: http://github.com/sminster/csm
  license: Unlicense
  license_file: LICENSE
  summary: The Community Sensor Model API
  description: |
    csm is a C++ API for terrestrial and planetary sensor models

extra:
  recipe-maintainers:
    - jlaura
