travis:
  secure:
    BINSTAR_TOKEN: unjP+BfARBopMP7A3V3h94xla6RURxMbitXIqI8vY08BgiGal0j8D3sztofopoRu/yipziC1aVFJXxtNTczS46al+fxhWSoYVQatzu7yLSbJlBJ1nBJdpGsQdpY4fAXlD+uDELjC3mIcAy6bQLTXDDuMpEakiakdQNswkszefSy8bR8p4OHhdq+0UxHIF/Z29/FWj1hRLIdmfD2zsTW655bfWNxukXcaTK3H1JpJPYm5Y7vZTlDikMe7T47JCXSx4pZARieoMdPwtfiiNF26xzmaDxG4cMif6Twr3NqGBTtof+iPNoJK7M8m6HxKIPMVzbZqB/UYMTdF2piN+jswIfaFdRSf7XyWvdLa8YmH9kKtR1dMhgK5t8lEvRWfoOqep1dRo0FfBd0cTNDWFC5LQ3WprMYWjIs8bOfWgKnq/xOJMOUl9fP2OIznldm9gXhKVOU+TrQQT7rq0kmYUcC2xvhufAA6FpN18N8V8d7Ffn2RIn6nZsQijpdLj+G89aSfV0Bv+ERLA0P7YK0juQOfa3wK1hmeEPCAbLrFfDt3fmTOB00sbXT9EWCOrEFnrsagBBJsgwdY/g3zmtmA6+3iOtBYVwZ8MRVkYTHSOosB0K8bS1uY5tqH3VwD83ZSKNuZFqNPhH+B6fOrR7kfBLtyLfuJr6OnPYimNeV1zdWl8Dw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
